#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionWebApi.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UnionBD")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDEPARTAMENTO(DEPARTAMENTO instance);
    partial void UpdateDEPARTAMENTO(DEPARTAMENTO instance);
    partial void DeleteDEPARTAMENTO(DEPARTAMENTO instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MiConexion"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DEPARTAMENTO> DEPARTAMENTOs
		{
			get
			{
				return this.GetTable<DEPARTAMENTO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPARTAMENTO")]
	public partial class DEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged,iKeyObject
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private int _I_ID;
		
		private string _DT_PK;
		
		private string _D_RESPONSABLE;
		
		private string _D_IMAGEN;
		
		private string _D_EMAIL;
		
		private string _D_TELEFONO;
		
		private System.Nullable<bool> _deleted;
		
		private System.Data.Linq.Binary _version;
		
		private System.DateTimeOffset _createdAt;
		
		private System.DateTimeOffset _updatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnI_IDChanging(int value);
    partial void OnI_IDChanged();
    partial void OnDT_PKChanging(string value);
    partial void OnDT_PKChanged();
    partial void OnD_RESPONSABLEChanging(string value);
    partial void OnD_RESPONSABLEChanged();
    partial void OnD_IMAGENChanging(string value);
    partial void OnD_IMAGENChanged();
    partial void OnD_EMAILChanging(string value);
    partial void OnD_EMAILChanged();
    partial void OnD_TELEFONOChanging(string value);
    partial void OnD_TELEFONOChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    partial void OnversionChanging(System.Data.Linq.Binary value);
    partial void OnversionChanged();
    partial void OncreatedAtChanging(System.DateTimeOffset value);
    partial void OncreatedAtChanged();
    partial void OnupdatedAtChanging(System.DateTimeOffset value);
    partial void OnupdatedAtChanged();
    #endregion
		
		public DEPARTAMENTO()
		{
			OnCreated();
		}

        string iKeyObject.Key
        {
            get
            {
                return this.Id.ToString();
            }

            set
            {
                throw new NotImplementedException();
            }
        }
        System.Data.Linq.Binary iKeyObject.Version
        {
            get
            {
                return this.version;
            }
        }
        System.Nullable<bool> iKeyObject.Deleted
        {
            get
            {
                return this.deleted;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_I_ID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int I_ID
		{
			get
			{
				return this._I_ID;
			}
			set
			{
				if ((this._I_ID != value))
				{
					this.OnI_IDChanging(value);
					this.SendPropertyChanging();
					this._I_ID = value;
					this.SendPropertyChanged("I_ID");
					this.OnI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_PK", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DT_PK
		{
			get
			{
				return this._DT_PK;
			}
			set
			{
				if ((this._DT_PK != value))
				{
					this.OnDT_PKChanging(value);
					this.SendPropertyChanging();
					this._DT_PK = value;
					this.SendPropertyChanged("DT_PK");
					this.OnDT_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_RESPONSABLE", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string D_RESPONSABLE
		{
			get
			{
				return this._D_RESPONSABLE;
			}
			set
			{
				if ((this._D_RESPONSABLE != value))
				{
					this.OnD_RESPONSABLEChanging(value);
					this.SendPropertyChanging();
					this._D_RESPONSABLE = value;
					this.SendPropertyChanged("D_RESPONSABLE");
					this.OnD_RESPONSABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_IMAGEN", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string D_IMAGEN
		{
			get
			{
				return this._D_IMAGEN;
			}
			set
			{
				if ((this._D_IMAGEN != value))
				{
					this.OnD_IMAGENChanging(value);
					this.SendPropertyChanging();
					this._D_IMAGEN = value;
					this.SendPropertyChanged("D_IMAGEN");
					this.OnD_IMAGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_EMAIL", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string D_EMAIL
		{
			get
			{
				return this._D_EMAIL;
			}
			set
			{
				if ((this._D_EMAIL != value))
				{
					this.OnD_EMAILChanging(value);
					this.SendPropertyChanging();
					this._D_EMAIL = value;
					this.SendPropertyChanged("D_EMAIL");
					this.OnD_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_TELEFONO", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string D_TELEFONO
		{
			get
			{
				return this._D_TELEFONO;
			}
			set
			{
				if ((this._D_TELEFONO != value))
				{
					this.OnD_TELEFONOChanging(value);
					this.SendPropertyChanging();
					this._D_TELEFONO = value;
					this.SendPropertyChanged("D_TELEFONO");
					this.OnD_TELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this.OnversionChanging(value);
					this.SendPropertyChanging();
					this._version = value;
					this.SendPropertyChanged("version");
					this.OnversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this.OnupdatedAtChanging(value);
					this.SendPropertyChanging();
					this._updatedAt = value;
					this.SendPropertyChanged("updatedAt");
					this.OnupdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
